"""
Attribute code mappings for Vanderbilt University system.

This module contains the mapping from full course attribute names to their 
abbreviated codes used throughout the Vanderbilt course system.
"""

ATTRIBUTE_MAP = {
    'AXLE: 1000-level W course': '100W',
    'AXLE: 2000-level and above W course': '200W',
    'AXLE: First-Year Writing Seminar': '115F',
    'AXLE: Foreign language proficiency': 'FL',
    'AXLE: History and Culture of the United States': 'US',
    'AXLE: Humanities and the Creative Arts': 'HCA',
    'AXLE: International Cultures': 'INT',
    'AXLE: Math and Natural Sciences': 'MNS',
    'AXLE: Oral Communications course': 'ORC',
    'AXLE: Perspectives': 'PSP',
    'AXLE: Social and Behavioral Sciences': 'SBS',
    'Accounting Concentration': 'ACCTC',
    'Acting Internship': 'AI',
    'Advanced Clinical Experience': 'ACE',
    'Advanced Elective': 'AE',
    'Brand Management Specialization': 'BMS',
    'CORE: A-Written & Creative Expression': 'A',
    'CORE: B-Systemic & Structural Reasoning': 'B',
    'CORE: C-Cultural & Interpretive Investigation': 'C',
    'CORE: D-Data Literacy & Computational Thinking': 'D',
    'CORE: E-Ethical & Social Engagement': 'E',
    'CORE: LA-World Language through 2nd Semester': 'LA',
    'CORE: LB-Inquiry Lab': 'LB',
    'Consumer Psych & Mark Analytics Concentration': 'CPMAC',
    'Core Clerkship': 'CC',
    'Core Clerkship Elective': 'CCE',
    'Corporate Finance Specialization': 'CFS',
    'DIVE: Design Thinking through Projects': 'DIVE',
    'Domestic Travel Required': 'DOM',
    'Electives': 'ELEC',
    'Eligible for African American and Diaspora Studies': 'AADS',
    'Eligible for American Studies Major': 'AMER',
    'Eligible for Ancient Mediterranean Studies': 'MS',
    'Eligible for Anthroplogy': 'ANTH',
    'Eligible for Art': 'ART',
    'Eligible for Asian Amer & Asian Diaspora Studies': 'ASAD',
    'Eligible for Asian Studies': 'ASIA',
    'Eligible for Chinese Studies': 'CHIN',
    'Eligible for Cinema and Media Arts': 'CMA',
    'Eligible for Classical Civilizations': 'CCIV',
    'Eligible for Classics': 'CLAS',
    'Eligible for Climate Studies': 'CLIM',
    'Eligible for Communication Studies': 'COMM',
    'Eligible for Communication of Science and Tech': 'COMMSCI',
    'Eligible for Data Science Minor': 'DS',
    'Eligible for Digital Fabrication': 'DF',
    'Eligible for Econ/Hist Interdisciplinary': 'EHST',
    'Eligible for Economics': 'ECON',
    'Eligible for English': 'ENGL',
    'Eligible for Environ. and Sustainability Studies': 'ENVS',
    'Eligible for Environmental Sociology': 'ESOC',
    'Eligible for Epidemiology': 'EPID',
    'Eligible for European Studies': 'EUS',
    'Eligible for Film Studies': 'FILM',
    'Eligible for French': 'FREN',
    'Eligible for Gender and Sexuality Studies': 'WGS',
    'Eligible for History': 'HIST',
    'Eligible for History of Art': 'HART',
    'Eligible for Human Genetics': 'HGEN',
    'Eligible for Islamic Studies': 'IMST',
    'Eligible for Jewish Studies': 'JS',
    'Eligible for Latin American Studies': 'LAT',
    'Eligible for Latino/Latina Studies': 'LATS',
    'Eligible for Law, History, and Society': 'LHS',
    'Eligible for Medicine Health and Society': 'MHS',
    'Eligible for Minor in Legal Studies': 'ULAW',
    'Eligible for Neuroscience': 'NSC',
    'Eligible for Philosophy': 'PHIL',
    'Eligible for Physics': 'PHYS',
    'Eligible for Political Science': 'PSCI',
    'Eligible for Portuguese': 'PORT',
    'Eligible for Psychology': 'PSY',
    'Eligible for Public Policy Studies': 'PPS',
    'Eligible for Religious Studies': 'RLST',
    'Eligible for Scientific Computing': 'SC',
    'Eligible for Sociology': 'SOC',
    'Eligible for Spanish': 'SPAN',
    'Eligible for Theatre': 'THTR',
    'Eligible for Undergraduate Business Minor': 'BUS',
    'Entrepreneurship Emphasis': 'EE',
    'Finance Concentration': 'FINC',
    'Foundational Science Course': 'FSC',
    'H&OP Concentration': 'HOPC',
    'H&OP Specialization': 'HOPS',
    'HOD Capstone': 'HOD CAP',
    'HOD Core': 'HOD CORE',
    'HOD Domain 1': 'HOD1',
    'HOD Domain 2': 'HOD2',
    'HOD Domain 3': 'HOD3',
    'Health Care Concentration': 'HCC',
    'Human & Organizational Development': 'HOD',
    'Immersion: Culminating': 'CULM',
    'Immersion: Exp. or Culm. (Instructor guidance)': 'EXPCULM',
    'Immersion: Experiential': 'EXP',
    'International Studies Emphasis': 'ISE',
    'Investment Management Specialization': 'IMS',
    'LE: HFA-Humanities and Fine Arts': 'LEHFA',
    'LE: MNS-Math and Natural Sciences': 'LEMNS',
    'LE: SBS-Social and Behavioral Sciences': 'LESBS',
    'Law and Business Class': 'LWBS',
    'Law in Venice': 'LIV',
    'Leadership, Policy & Organization Dept': 'LPO',
    'MAcc Assurance': 'MACCA',
    'MAcc Val': 'MACCVAL',
    'MBA Program': 'MBA',
    'MBA Required Course': 'MBARC',
    'MD Clerkship Elective': 'MD CLE',
    'MED: Foundations of Clinical Care Phase': 'FCC',
    'MED: Foundations of Medical Knowledge Phase': 'FMK',
    'MED: Immersion Phase': 'IMM',
    'MED: Integrated Science Course': 'ISC',
    'MED: Learning Communities': 'LC',
    'MED: Miscellaneous': 'MISC',
    'MED: Research': 'RES',
    'MMark': 'MMARK',
    'MSF Primary Elective': 'MSFPE',
    'MSF Program': 'MSF',
    'MSF Secondary Elective': 'MSFSE',
    'Marketing Concentration': 'MC',
    'Medical Innovators Dev Program': 'MIDP',
    'Military Science Course, Army': 'ARMY',
    'Military Science Course, Navy': 'NAVY',
    'Next Steps Eligible': 'NEXT',
    'Ops & Analytics Concentration': 'OAC',
    'Overseas Travel Required': 'INTL',
    'Professional Skills': 'PRSK',
    'Psychological Sciences Course (Graduate School)': 'PSY-GS',
    'Service Learning': 'SL',
    'Strategy Concentration': 'SC',
    'Sustainability & Social Impact Emphasis': 'SSIE',
    'Travel Fee Applies': 'FEE',
    'iSeminar': 'COMMSEM'
}
