"""
Subject code mappings for Vanderbilt University system.

This module contains the mapping from full subject/department names to their
abbreviated codes used throughout the Vanderbilt course system.
"""

SUBJECT_MAP = {
    'A&S College Core': 'CORE',
    'African American and Diaspora Studies': 'AADS',
    'American Sign Language': 'ASL',
    'American Studies': 'AMER',
    'Anesthesiology': 'ANES',
    'Anthropology': 'ANTH',
    'Applied Clinical Informatics': 'ACI',
    'Arabic': 'ARA',
    'Aramaic and Syriac': 'ARAM',
    'Art Studio': 'ARTS',
    'Asian Studies': 'ASIA',
    'Asian-American Studies': 'ASAM',
    'Astronomy': 'ASTR',
    'Audiology': 'AUD',
    'Baroque perform instruction in string instruments': 'BRQ',
    'Biochemistry & Chemical Biology': 'BCB',
    'Biochemistry (GS)': 'BCHM-GS',
    'Biological Sciences': 'BSCI',
    'Biomedical Engineering': 'BME',
    'Biomedical Informatics (GS)': 'BMIF',
    'Biomedical Sciences': 'BMS',
    'Biostatistics': 'BIOS',
    'Business': 'BUS',
    'Business - OGSM': 'BUSO',
    'Business-Arts&Science': 'BUSA',
    'Cancer Biology (GS)': 'CANB',
    'Career Development': 'CAR',
    'Catalan': 'CTLN',
    'Cell Biology': 'CBIO-GS',
    'Chemical and Biomolecular Engineering': 'CHBE',
    'Chemical and Physical Biology': 'CPBP',
    'Chemistry': 'CHEM',
    'Cherokee': 'CHRK',
    'Chinese': 'CHIN',
    'Cinema and Media Arts': 'CMA',
    'Civil Engineering': 'CE',
    'Classical Hebrew': 'CHEB',
    'Classics': 'CLAS',
    'Clinical Investigation': 'MSCI',
    'Communication Studies': 'CMST',
    'Communication of Science and Technology': 'CSET',
    'Comparative Media Analysis and Practice': 'CMAP',
    'Computer Science': 'CS',
    'Conducting': 'MCON',
    'Culture, Advocacy, Leadership': 'CAL',
    'Dance History': 'DANC',
    'Data Science': 'DS',
    'Data Science A&S': 'DSA&S',
    'Data Science Blair': 'DSBLR',
    'Data Science DIV': 'DSDIV',
    'Data Science Engineering': 'DSENG',
    'Data Science GS': 'DSGS',
    'Data Science GSM': 'DSGSM',
    'Data Science LAW': 'DSLAW',
    'Data Science Peabody': 'DSPBY',
    'Data Science SOM': 'DSSOM',
    'Data Science SON': 'DSSON',
    'Dermatology': 'DERM',
    'Diagnostic Radiology': 'RAMD',
    'Digital Fabrication': 'DF',
    'Digital Humanities': 'DHUM',
    'Divinity': 'DIV',
    'Earth and Environmental Sciences': 'EES',
    'Economics': 'ECON',
    'Education': 'EDUC',
    'Education Of The Deaf': 'MDE',
    'Education Policy': 'EDP',
    'Education and Higher Education Leadership and Poli': 'EHLP',
    'Educational Leadership and Policy': 'ELP',
    'Electrical & Computer Engineering': 'EECE',
    'Emergency Medicine': 'EM',
    'Engineering Management': 'ENGM',
    'Engineering Science': 'ES',
    'English': 'ENGL',
    'English Education': 'ENED',
    'Ensembles': 'MUSE',
    'Environmental Engineering': 'ENVE',
    'Environmental and Sustainability Studies': 'ENVS',
    'Epidemiology': 'EPID',
    'Estab Multi_Astron Inclusive': 'EMIT',
    'European Studies': 'EUS',
    'Executive Management': 'EMGT',
    'Family Medicine': 'FM',
    'Financial Economics': 'FNEC',
    'Foreign Language Education': 'FLED',
    'Foreign Program Work': 'FNTM',
    'Foreign Programs-Blair': 'FNTB',
    'Foreign Programs-Engineering': 'FNTE',
    'French': 'FREN',
    'Gender and Sexuality Studies': 'GSS',
    'General Elective': 'GNEL',
    'Genetic Counseling': 'GC',
    'German': 'GER',
    'Global Health (MD)': 'IGHM',
    'Greek': 'GRK',
    'H&OD: Community Leadership and Development': 'HODC',
    'H&OD: Education Policy': 'HODE',
    'H&OD: Health and Human Services': 'HODH',
    'H&OD: International Leadership and Policy': 'HODI',
    'H&OD: Leadership and Organizational Effectiveness': 'HODL',
    'Haitian Creole Language': 'CREO',
    'Health Policy': 'HPOL',
    'Hearing & Speech Sciences': 'HRSP',
    'Hebrew': 'HEBR',
    'Higher Education Administration': 'HEA',
    'Higher Education Leadership and Policy': 'HLP',
    'Hindi Urdu Language Instruction': 'HNUR',
    'History': 'HIST',
    'History (FK)': 'HIST-FK',
    'History Of Art': 'HART',
    'Honors': 'HONS',
    'Honors (Fisk)': 'HON-FK',
    'Human & Organizational Development': 'HOD',
    'Human Development Counseling': 'HDCO',
    'Human Development Studies': 'HDS',
    'Human Genetics': 'HGEN',
    'Humanities': 'HUM',
    'Humanities Education-PC': 'HMED',
    'Imaging Science': 'IMSCI',
    'Immersion Vanderbilt': 'IMM',
    'Independent School Leadership': 'ISL',
    'Interdisciplinary (GS)': 'INTE',
    'Interdisciplinary Grad Programs': 'IGP',
    'Interdisciplinary Materials Science': 'IMS',
    'Interdisciplinary Studies': 'INDS',
    'Interdisciplinary-MED': 'IDIS',
    'International Education and Policy Management': 'IEPM',
    'Italian': 'ITA',
    'Japanese': 'JAPN',
    'Jazz and Global Music': 'JAZZ',
    'Jewish Studies': 'JS',
    'K\'iche\' - Mayan Language': 'KICH',
    'Keyboard Harmony': 'MUKH',
    'Korean': 'KOR',
    'Laboratory Investigation': 'MLI',
    'Latin': 'LAT',
    'Latin Amer Caribbean Studies': 'LACX',
    'Latin American Studies': 'LAS',
    'Latino and Latina Studies': 'LATS',
    'Law': 'LAW',
    'Law and Economics': 'LWEC',
    'Leadership and Learning in Organizations': 'LLO',
    'Leadership and Organizational Performance': 'LOP',
    'Leadership, Policy & Organization': 'LPO',
    'Leading Organizations': 'MLO',
    'Malagasy': 'MALA',
    'Management-OWEN': 'MGT',
    'Managerial Studies': 'MGRL',
    'Master of Legal Studies': 'MLS',
    'Master of Liberal Arts and Science': 'MLAS',
    'Materials Science & Engineering': 'MSE',
    'Math Education': 'MTED',
    'Mathematics': 'MATH',
    'Mechanical Engineering': 'ME',
    'Medical Administration': 'MADM',
    'Medical Scientist Training Prog': 'MSTP',
    'Medicine': 'MED',
    'Medicine, Health, and Society': 'MHS',
    'Microbe - Host Interactions': 'M&IM',
    'Military Science': 'MS',
    'Military Science-PC': 'MS-PC',
    'Minor in Legal Studies': 'ULAW',
    'Molecular Pathology and Immunology': 'PATH-GS',
    'Molecular Physiology and Biophysics': 'MP&B',
    'Multilingual Learner Education': 'EDML',
    'Music Business/Entrepreneurshp': 'MENT',
    'Music Composition': 'COMP',
    'Music Pedagogy': 'MPED',
    'Music Repertoire/Literature': 'MREP',
    'Music Teacher Education': 'MUED',
    'Music Technology': 'MTEC',
    'Music Theory': 'MUTH',
    'Musicians\' Wellness': 'MWEL',
    'Musicianship': 'MUSC',
    'Musicology/Ethnomusicology': 'MUSL',
    'Nanoscience and Nanotechnology': 'NANO',
    'Naval Science': 'NS',
    'Naval Science - Peabody': 'NS-PC',
    'Neurodiversity Inspired Science and Engineering': 'NISE',
    'Neurology': 'NEUR',
    'Neuroscience': 'NSC',
    'Neuroscience (GS)': 'NURO',
    'Next Steps': 'NEXT',
    'Nursing': 'NURS',
    'Nursing Science': 'NRSC',
    'Obstetrics & Gynecology': 'OBGN',
    'Ophthalmology': 'OPH',
    'Oral and Maxillofacial Surgery': 'OMFS',
    'Orthopaedics & Rehabilitation': 'ORTH',
    'Other Music Courses': 'MUSO',
    'Otolaryngology': 'OTO',
    'Pathology-MED': 'PATH',
    'Peabody College': 'PBDY',
    'Peabody Honors Scholars': 'PSCH',
    'Peabody Summer Internship Experience': 'PINX',
    'Peabody Vanderbilt Abroad': 'PVUA',
    'Pediatric Medicine': 'PED',
    'Performance Instruction: Banjo': 'BNJO',
    'Performance Instruction: Bass': 'BASS',
    'Performance Instruction: Bassoon': 'BSSN',
    'Performance Instruction: Cello': 'CLLO',
    'Performance Instruction: Clarinet': 'CLAR',
    'Performance Instruction: Drumset': 'DRUM',
    'Performance Instruction: Euphonium': 'EUPH',
    'Performance Instruction: Fiddle': 'FDDL',
    'Performance Instruction: Flute': 'FLUT',
    'Performance Instruction: Guitar Classical': 'GTR',
    'Performance Instruction: Harp': 'HARP',
    'Performance Instruction: Harpsichord': 'HRPS',
    'Performance Instruction: Horn': 'HORN',
    'Performance Instruction: Mandolin': 'MNDL',
    'Performance Instruction: Oboe': 'OBOE',
    'Performance Instruction: Organ': 'ORGN',
    'Performance Instruction: Percussion': 'PERC',
    'Performance Instruction: Piano': 'PIAN',
    'Performance Instruction: Saxophone': 'SAX',
    'Performance Instruction: Steel Pan': 'STPN',
    'Performance Instruction: Trombone': 'TROM',
    'Performance Instruction: Trumpet': 'TRPT',
    'Performance Instruction: Tuba': 'TUBA',
    'Performance Instruction: Viola': 'VLA',
    'Performance Instruction: Violin': 'VLN',
    'Performance Instruction: Voice': 'VOIC',
    'Persian': 'PERS',
    'Pharmacology (GS)': 'PHAR-GS',
    'Philosophy': 'PHIL',
    'Physical Medicine and Rehabilitation': 'PMR',
    'Physics': 'PHYS',
    'Political Economy': 'PECN',
    'Political Science': 'PSCI',
    'Portuguese': 'PORT',
    'Preventive Medicine': 'PM',
    'Psychiatry': 'PSYCH',
    'Psychology (AS)': 'PSY',
    'Psychology and Human Development (GS)': 'PSY-GS',
    'Psychology-PC': 'PSY-PC',
    'Public Health': 'PUBH',
    'Public Policy Studies': 'PPS',
    'Radiation Oncology': 'RADO',
    'Radiology': 'RAD',
    'Religion': 'REL',
    'Religious Studies': 'RLST',
    'Responsible Conduct in Research': 'RCRG',
    'Robert Penn Warren Center': 'RPW',
    'Russian': 'RUSS',
    'Sanskrit': 'SNSK',
    'Science Education': 'SCED',
    'Scientific Computing': 'SC',
    'Second Language Studies': 'SLS',
    'Social Studies Education': 'SSED',
    'Sociology': 'SOC',
    'Spanish': 'SPAN',
    'Special Education': 'SPED',
    'Special Education Certificate': 'SPEDC',
    'Special Education Multiple and Severe Disabilities': 'SPEDS',
    'Special Education: Early Childhood Education': 'SPEDE',
    'Special Education: High Incidence': 'SPEDH',
    'Special Education: Visual Impairments': 'SPEDV',
    'Speech Language Pathology': 'SLP',
    'Surgery': 'SURG',
    'Swahili Language': 'SWAH',
    'Theatre': 'THTR',
    'Therapeutic Radiology': 'RAMT',
    'Tibetan Language': 'TBTN',
    'Turkish Language': 'TURK',
    'University Courses': 'UNIV',
    'Urologic Surgery': 'UROL',
    'Vanderbilt Visions': 'VV',
    'Women\'s and Gender Studies': 'WGS',
    'World Languages': 'WLED',
    'X Computer Science': 'XCS',
    'X Electrical & Comp Engineering': 'XECE'
}
